---
permalink: intro-family.html 
keywords: introduction, how astra works, how Astra works, what Astra is, astra control, kubernetes, astra control service, astra control center 
summary: Astra è un servizio di gestione del ciclo di vita dei dati delle applicazioni Kubernetes che semplifica le operazioni per le applicazioni stateful. Proteggi, esegui il backup e migra facilmente i carichi di lavoro Kubernetes e crea istantaneamente cloni applicativi funzionanti. 
---
= Scopri di più su Astra Control
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Astra Control è una soluzione di gestione del ciclo di vita dei dati delle applicazioni Kubernetes che semplifica le operazioni per le applicazioni con stato e ti aiuta ad archiviare, proteggere e spostare i tuoi carichi di lavoro Kubernetes su ambienti ibridi.



== Funzionalità

Astra Control offre funzionalità critiche per la gestione del ciclo di vita dei dati delle applicazioni Kubernetes:

*Negozio*:

* Provisioning dello storage dinamico per i carichi di lavoro in container
* Crittografia in-flight dei dati da container a volumi persistenti
* Replica tra aree e aree


*Protezione*:

* Rilevamento automatizzato e protezione integrata con l'applicazione di un'intera applicazione e dei relativi dati
* Ripristino istantaneo di un'applicazione da qualsiasi versione snapshot in base alle esigenze dell'organizzazione
* Failover rapido tra zone, aree e cloud provider


*Sposta*:

* Mobilità completa di applicazioni e dati all'interno e tra cluster Kubernetes e cloud
* Cloni istantanei di intere applicazioni e dati
* Migrazione delle applicazioni con un solo clic tramite API e UI web coerenti




== Architettura

L'architettura di Astra Control consente all'IT di fornire funzionalità avanzate di gestione dei dati che migliorano sia la funzionalità che la disponibilità delle applicazioni Kubernetes, semplificano la gestione, la protezione e lo spostamento dei carichi di lavoro in container nei cloud pubblici e negli ambienti on-premise. inoltre, offre funzionalità di automazione tramite API REST e SDK, consentendo l'accesso programmatico per un'integrazione perfetta con i flussi di lavoro esistenti.

Astra Control è nativo di Kubernetes e consente workflow di data Protection che utilizzano risorse personalizzate pur rimanendo compatibile con le versioni precedenti dell'API e dell'SDK esistenti. La data Protection nativa di Kubernetes offre vantaggi significativi: Con l'integrazione perfetta con le risorse e le API Kubernetes, la data Protection può diventare una parte integrante del ciclo di vita delle applicazioni attraverso gli strumenti ci/CD e/o GitOps esistenti dell'organizzazione.

Astra Control è costruito su quattro componenti complementari:

* *Astra Control*: Astra Control è il servizio di gestione centralizzato per tutti i cluster gestiti, che fornisce carichi di lavoro orchestrati per la protezione e la mobilità delle applicazioni in locale, nonché le seguenti funzionalità:
+
** Vista combinata di più cluster
** Protezione dei flussi di lavoro orchestrati
** Visualizzazione e selezione granulare delle risorse


* *Astra Connector*: Astra Connector raggruppa Astra Control per fornire una connessione sicura a ciascun cluster gestito, offrendo l'esecuzione locale delle operazioni pianificate indipendentemente dallo stato della connessione e le seguenti funzionalità:
+
** Esecuzione locale delle operazioni pianificate indipendentemente dallo stato della connessione
** Operazioni locali che distribuiscono e ottimizzano l'utilizzo delle risorse di sistema di Astra tra i cluster
** Installazione locale che consente l'accesso con privilegi minimi al cluster per una maggiore sicurezza


* *Astra Control Provisioner*: Astra Control Provisioner offre funzionalità di provisioning CSI core e capacità di gestione dello storage avanzate per una maggiore sicurezza e configurazione di disaster recovery, nonché le seguenti capacità:
+
** Provisioning dello storage dinamico per i carichi di lavoro in container
** Gestione avanzata dello storage:
+
*** Crittografia in-flight dei dati da container a PV
*** Funzionalità SnapMirror Cloud con replica tra aree e zone




* *Astra Custom Resources*: Le risorse personalizzate utilizzate su ogni cluster forniscono un approccio nativo per Kubernetes per l'esecuzione delle operazioni in locale, semplificando l'integrazione con altri tool e automazione compatibili con Kubernetes e fornendo le seguenti funzionalità:
+
** Flussi di lavoro diretti di automazione e integrazione degli strumenti dell'ecosistema
** Primitive di livello inferiore che abilitano flussi di lavoro personalizzati






== Modelli di implementazione

Astra Control è disponibile in un unico modello di distribuzione.

*Astra Control Center*: Software autogestito che fornisce la gestione dei dati applicativa dei cluster Kubernetes in esecuzione nel tuo ambiente on-premise. Il centro di controllo Astra può essere installato anche in ambienti di cloud provider multipli con un backend di storage NetApp Cloud Volumes ONTAP.

https://docs.netapp.com/us-en/astra-control-center/["Documentazione di Astra Control Center"^]

[cols="1h,2d"]
|===
|  | Centro di controllo Astra 


| Come viene offerto? | Come software che puoi scaricare, installare e gestire 


| Dove è ospitato? | Sul tuo cluster Kubernetes 


| Come viene aggiornato? | Gli aggiornamenti vengono gestiti 


| Quali sono le distribuzioni Kubernetes supportate?  a| 
* Azure Kubernetes Service su Azure Stack HCI
* Google anthos
* Kubernetes (upstream)
* Rancher Kubernetes Engine (RKE)
* Red Hat OpenShift Container Platform




| Quali sono i backend di storage supportati?  a| 
* Sistemi NetApp ONTAP AFF e FAS
* NetApp ONTAP Select
* https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/["Cloud Volumes ONTAP"^]
* https://longhorn.io/["Longhorn"^]


|===


== Per ulteriori informazioni

* https://docs.netapp.com/us-en/astra-control-center/["Documentazione di Astra Control Center"^]
* https://docs.netapp.com/us-en/trident/index.html["Documentazione di Astra Trident"^]
* https://docs.netapp.com/us-en/astra-automation/index.html["API di controllo Astra"^]
* https://docs.netapp.com/us-en/cloudinsights/["Documentazione Cloud Insights"^]
* https://docs.netapp.com/us-en/ontap/index.html["Documentazione ONTAP"^]

